<a href="https://colab.research.google.com/github/MrRuicy/colab/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)
print("CUDA Available:", torch.cuda.is_available())


2.8.0+cu126
CUDA Available: True


In [3]:
import torch

# 创建一个张量
x = torch.ones(3, 3, requires_grad=True)
print("x =", x)

# 做一个操作
y = x + 2
print("y =", y)

# 再做一个操作
z = y * y * 3
print("z =", z)

out = z.mean()
print("out =", out)

# 反向传播
out.backward()
print("x.grad =", x.grad)


x = tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
y = tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)
z = tensor([[27., 27., 27.],
        [27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>)
out = tensor(27., grad_fn=<MeanBackward0>)
x.grad = tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [4]:
# 1. 创建张量
x = torch.tensor([[1, 2], [3, 4]])
print("x =\n", x)

# 2. 张量类型
print("数据类型:", x.dtype)
print("设备（CPU/GPU）:", x.device)

# 3. 张量运算
y = x + 2
z = x * y
print("y =\n", y)
print("z =\n", z)

# 4. 用随机值创建张量
a = torch.rand(2, 3)
print("a =\n", a)


x =
 tensor([[1, 2],
        [3, 4]])
数据类型: torch.int64
设备（CPU/GPU）: cpu
y =
 tensor([[3, 4],
        [5, 6]])
z =
 tensor([[ 3,  8],
        [15, 24]])
a =
 tensor([[0.7742, 0.2535, 0.8821],
        [0.6702, 0.8418, 0.1077]])


In [5]:
t1 = torch.arange(10)
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
t2 = t1.reshape(2,5)
t2


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
t3 = torch.rand(2,3,4)
t3

tensor([[[0.3585, 0.7658, 0.3550, 0.8845],
         [0.4852, 0.0382, 0.4785, 0.1348],
         [0.8023, 0.4535, 0.3893, 0.2591]],

        [[0.5045, 0.6463, 0.9077, 0.9922],
         [0.7986, 0.3666, 0.3174, 0.6451],
         [0.3474, 0.8839, 0.1581, 0.9069]]])

In [8]:
# 创建一个张量，并设置需要梯度
# 定义的 y = x^2 + 3x + 1 自动构建了计算图，调用 backward() 会从输出层开始求梯度。
x = torch.tensor(3., requires_grad=True) #Only Tensors of floating point and complex dtype can require gradients

# 定义一个简单计算图
y = x ** 2 + 3 * x + 1

# 执行反向传播
y.backward()

# 梯度
print("dy/dx =", x.grad)

# 即2*x+3

dy/dx = tensor(9.)


In [9]:
# 检查 GPU
print("CUDA Available:", torch.cuda.is_available())

# 创建张量到 GPU
if torch.cuda.is_available():
    x = torch.ones(3, 3).to("cuda")
    print("x on GPU:\n", x)
else:
    print("GPU 不可用，继续使用 CPU")


CUDA Available: True
x on GPU:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [10]:
import torch

# 1. 训练数据：y = 2x + 3
x = torch.randn(100, 1)
y = 2 * x + 3 + 0.1 * torch.randn(100, 1)

# 2. 初始化参数（权重和偏置）
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# 3. 学习率和训练目标
lr = 0.1

for epoch in range(50):
    # 前向传播
    y_pred = w * x + b
    loss = ((y_pred - y)**2).mean()  # 均方误差损失

    # 反向传播
    loss.backward()

    # 更新参数
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad

        # 清零梯度
        w.grad.zero_()
        b.grad.zero_()

    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

print("\n训练结束:")
print("学到的 w:", w.item())
print("学到的 b:", b.item())


Epoch 10, Loss: 0.3285
Epoch 20, Loss: 0.0116
Epoch 30, Loss: 0.0088
Epoch 40, Loss: 0.0088
Epoch 50, Loss: 0.0088

训练结束:
学到的 w: 1.9979472160339355
学到的 b: 3.011281728744507
